//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ictect.IntelliDocs.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public int dirId { get; set; }
        public Nullable<short> nodeLevel { get; set; }
        public string dirName { get; set; }
        public int Library_libId { get; set; }
        public System.DateTime dirCreateDate { get; set; }
    
        public virtual Library Library { get; set; }
    }
}
